# ==========================
# SERVER
# ==========================
server.port=8080

# ==========================
# POSTGRESQL
# ==========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskmanager_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================
# JPA / HIBERNATE
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ==========================
# JWT
# ==========================
jwt.secret=${JWT_SECRET:ThisIsA32PlusCharacterLongSecretKeyForJWTSigning123}
jwt.expiration-ms=86400000

# ==========================
# CORS
# ==========================
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}